### ISSUE TITLE
Reports: add 'will be compliant' metric

### ISSUE THREAD

**Issue by jesusbagpuss** [eprintsug/hefce_oa#33]
Currently reports show when an item is or isn't compliant.
The new 'will be compliant' display of an item will probably need representation in the Reports.

**Comment by wfyson** [comment]
This sounds sensible, although as far as I can tell the Generic Reporting Framework only allows for the reporting of problems or a complete lack of problems. I suspect the best way around this would therefore be to update the Generic Reporting Framework to display warnings in some way (so that it is just generally more flexible) and then we can add warnings to REF CC... probably a problem best left for another time however!

**Comment by wfyson** [comment]
For now I've added a bullet point to highlight when something meets the "will be compliant" criteria: https://github.com/eprintsug/hefce_oa/commit/cd860d4dbd84bbf0d687613772729b53e0d01c7e
